os: linux

language: go

go:
  - 1.14.x
env:
  GO111MODULE=on

script:
  - sudo docker system prune -a --volumes
  - sudo docker-compose -f docker-compose.yaml -f docker-compose.test.yaml up --exit-code-from test
